### ISSUE TITLE
Build fails on Ubuntu 14.04 (g++ 4.8.4 opencv 3.0)

### ISSUE THREAD

**Issue by nzjrs** [cheind/inpaint#3]
I haven't got this to build yet, but have encountered the following warnings at least

Build failure fixed with the following
```
diff --git a/src/criminisi_inpainter.cpp b/src/criminisi_inpainter.cpp
index c23e912..55415fe 100644
--- a/src/criminisi_inpainter.cpp
+++ b/src/criminisi_inpainter.cpp
@@ -17,6 +17,8 @@
    along with Inpaint.  If not, see <http://www.gnu.org/licenses/>.
 */
 
+#include <limits>
+
 #include <inpaint/criminisi_inpainter.h>
 #include <inpaint/patch.h>
 #include <inpaint/timer.h>
@@ -315,4 +317,4 @@ namespace Inpaint {
 
         ci.image().copyTo(image.getMat());
     }
-}
\ No newline at end of file
+}
```

Build warning - maybe specify std c++11 in CMake?
```
/tmp/inpaint/src/template_match_candidates.cpp: In member function ‘void Inpaint::TemplateMatchCandidates::removeInvalidBlocks(const cv::Mat&, std::vector<cv::Rect_<int> >&)’:
/tmp/inpaint/src/template_match_candidates.cpp:220:13: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
             }), rects.end())
```

And ultimately build fails with
```
/tmp/inpaint/src/template_match_candidates.cpp:220:14: error: no matching function for call to ‘remove_if(std::vector<cv::Rect_<int> >::iterator, std::vector<cv::Rect_<int> >::iterator, Inpaint::TemplateMatchCandidates::removeInvalidBlocks(const cv::Mat&, std::vector<cv::Rect_<int> >&)::__lambda0)’
             }), rects.end());
              ^
/tmp/inpaint/src/template_match_candidates.cpp:220:14: note: candidate is:
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /tmp/inpaint/src/template_match_candidates.cpp:20:
/usr/include/c++/4.8/bits/stl_algo.h:1134:5: note: template<class _FIter, class _Predicate> _FIter std::remove_if(_FIter, _FIter, _Predicate)
     remove_if(_ForwardIterator __first, _ForwardIterator __last,
     ^
/usr/include/c++/4.8/bits/stl_algo.h:1134:5: note:   template argument deduction/substitution failed:
/tmp/inpaint/src/template_match_candidates.cpp: In substitution of ‘template<class _FIter, class _Predicate> _FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = __gnu_cxx::__normal_iterator<cv::Rect_<int>*, std::vector<cv::Rect_<int> > >; _Predicate = Inpaint::TemplateMatchCandidates::removeInvalidBlocks(const cv::Mat&, std::vector<cv::Rect_<int> >&)::__lambda0]’:
/tmp/inpaint/src/template_match_candidates.cpp:220:14:   required from here
/tmp/inpaint/src/template_match_candidates.cpp:220:14: error: template argument for ‘template<class _FIter, class _Predicate> _FIter std::remove_if(_FIter, _FIter, _Predicate)’ uses local type ‘Inpaint::TemplateMatchCandidates::removeInvalidBlocks(const cv::Mat&, std::vector<cv::Rect_<int> >&)::__lambda0’
             }), rects.end());
              ^
/tmp/inpaint/src/template_match_candidates.cpp:220:14: error:   trying to instantiate ‘template<class _FIter, class _Predicate> _FIter std::remove_if(_FIter, _FIter, _Predicate)’
/tmp/inpaint/src/template_match_candidates.cpp: In function ‘void Inpaint::findTemplateMatchCandidates(cv::InputArray, cv::InputArray, cv::InputArray, cv::OutputArray, cv::Size, int, float)’:
/tmp/inpaint/src/template_match_candidates.cpp:245:117: error: no matching function for call to ‘Inpaint::TemplateMatchCandidates::findCandidates(cv::Mat, cv::Mat, cv::Mat, int&, float&)’
         tmc.findCandidates(templ.getMat(), templMask.getMat(), candidates.getMat(), maxWeakErrors, maxMeanDifference);
                                                                                                                     ^
/tmp/inpaint/src/template_match_candidates.cpp:245:117: note: candidate is:
/tmp/inpaint/src/template_match_candidates.cpp:66:10: note: void Inpaint::TemplateMatchCandidates::findCandidates(const cv::Mat&, const cv::Mat&, cv::Mat&, int, float)
     void TemplateMatchCandidates::findCandidates(
          ^
/tmp/inpaint/src/template_match_candidates.cpp:66:10: note:   no known conversion for argument 3 from ‘cv::Mat’ to ‘cv::Mat&’
make[2]: *** [CMakeFiles/inpaint.dir/src/template_match_candidates.cpp.o] Error 1
make[1]: *** [CMakeFiles/inpaint.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cheind** [comment]
Yes that seems to be a C++11 issue. Could you try to add ```set (CMAKE_CXX_STANDARD 11)``` in the cmake file at the very beginning?

**Comment by nzjrs** [comment]
The following fixes those issues.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 246f8bb..57c87e0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -11,6 +11,13 @@ find_package(OpenCV REQUIRED)
 
 include_directories(${OpenCV_INCLUDE_DIRS} "inc")
 
+if (CMAKE_VERSION VERSION_LESS "3.1")
+    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
+        set (CMAKE_CXX_FLAGS "--std=gnu++11 ${CMAKE_CXX_FLAGS}")
+    endif ()
+    else ()
+        set (CMAKE_CXX_STANDARD 11)
+endif ()
 
 # Library
 
@@ -59,4 +66,4 @@ add_executable(inpaint_benchmarks
        benchmarks/catch.hpp
        benchmarks/patch.cpp    
 )
-target_link_libraries (inpaint_benchmarks inpaint ${OpenCV_LIBRARIES})
\ No newline at end of file
+target_link_libraries (inpaint_benchmarks inpaint ${OpenCV_LIBRARIES})
```

I get some build failures with CV3 as you expect.

**Comment by cheind** [comment]
@nzjrs thanks for fixing this. I'm at a conference right now, so I will incorporate your fixes next week when I'm back.

**Comment by cheind** [comment]
@nzjrs finally pushed the necessary commits to make it work. Fixed an error in tests along with it. For me it works on OpenCV 3.1, could you give the latest version on master a try?

**Comment by nzjrs** [comment]
Thanks a lot.

With OpenCV 3.0 it fails with
```
/tmp/inpaint/src/template_match_candidates.cpp: In function ‘void Inpaint::findTemplateMatchCandidates(cv::InputArray, cv::InputArray, cv::InputArray, cv::OutputArray, cv::Size, int, float)’:
/tmp/inpaint/src/template_match_candidates.cpp:243:117: error: no matching function for call to ‘Inpaint::TemplateMatchCandidates::findCandidates(cv::Mat, cv::Mat, cv::Mat, int&, float&)’
         tmc.findCandidates(templ.getMat(), templMask.getMat(), candidates.getMat(), maxWeakErrors, maxMeanDifference);
                                                                                                                     ^
/tmp/inpaint/src/template_match_candidates.cpp:243:117: note: candidate is:
/tmp/inpaint/src/template_match_candidates.cpp:64:10: note: void Inpaint::TemplateMatchCandidates::findCandidates(const cv::Mat&, const cv::Mat&, cv::Mat&, int, float)
     void TemplateMatchCandidates::findCandidates(
          ^
/tmp/inpaint/src/template_match_candidates.cpp:64:10: note:   no known conversion for argument 3 from ‘cv::Mat’ to ‘cv::Mat&’
```

**Comment by cheind** [comment]
@nzjrs ok I think that should be resolve now.

**Comment by nzjrs** [comment]
Thanks for looking into this so quickly!

A few other notes:

* Cmake should check for libtbb (I previously got a link failure as it wasn't installed)
* there remains two errors

```
In file included from /tmp/inpaint/inc/inpaint/patch.h:23:0,
                 from /tmp/inpaint/inc/inpaint/patch_match.h:23,
                 from /tmp/inpaint/src/patch_match.cpp:20:
/tmp/inpaint/inc/inpaint/stats.h: In function ‘T Inpaint::minimum(T, T)’:
/tmp/inpaint/inc/inpaint/stats.h:29:17: error: ‘min’ is not a member of ‘std’
         return (std::min<T>)(a, b);
```
is fixed with
```
diff --git a/inc/inpaint/stats.h b/inc/inpaint/stats.h
index f394eaf..828cc8a 100644
--- a/inc/inpaint/stats.h
+++ b/inc/inpaint/stats.h
@@ -20,6 +20,8 @@
 #ifndef INPAINT_STATS_H
 #define INPAINT_STATS_H
 
+#include <algorithm>
+
 namespace Inpaint {
 
     /** Minimum of two */
@@ -69,4 +71,4 @@ namespace Inpaint {
     }
 
 }
-#endif
\ No newline at end of file
+#endif
```

and

```
In file included from /tmp/inpaint/tests/gradient.cpp:24:0:
/tmp/inpaint/inc/inpaint/gradient.h: In function ‘cv::Vec2f Inpaint::gradient(const Mat&, int, int)’:
/tmp/inpaint/inc/inpaint/gradient.h:44:24: error: expected primary-expression before ‘>’ token
             m.ptr<uchar>(y-1),
                        ^
/tmp/inpaint/inc/inpaint/gradient.h:45:24: error: expected primary-expression before ‘>’ token
             m.ptr<uchar>(y),
                        ^
/tmp/inpaint/inc/inpaint/gradient.h:46:24: error: expected primary-expression before ‘>’ token
             m.ptr<uchar>(y+1)
                        ^
make[2]: *** [CMakeFiles/inpaint_tests.dir/tests/gradient.cpp.o] Error 1
make[1]: *** [CMakeFiles/inpaint_tests.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by nzjrs** [comment]
That is a strange error considering the following file compiles OK
```c++
#include <opencv2/highgui/highgui.hpp>
#include <iostream>

using namespace std;
using namespace cv;

void gradient(const Mat &m, int y, int x)
{
    const uchar *rows[3] = {
        m.ptr<uchar>(y-1),
        m.ptr<uchar>(y),
        m.ptr<uchar>(y+1)
    };
}

int main(void)
{
    Mat img1 = imread("test.jpg",CV_LOAD_IMAGE_GRAYSCALE);
    gradient(img1, 5, 5);
}
```

```bash
g++ -std=c++11 test.cpp -o test `pkg-config opencv --cflags --libs`
```

**Comment by cheind** [comment]
Do you run the latest gcc?

**Comment by nzjrs** [comment]
I'm running the default on Ubuntu 14.04

g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by nzjrs** [comment]
Sorry, I missed your edit.

```
        const unsigned char *rows[3] = {
            m.ptr<unsigned char>(y-1),
            m.ptr<unsigned char>(y),
            m.ptr<unsigned char>(y+1)
        };
```

results in the following error

```
In file included from /home/stowers/Programming/inpaint/tests/gradient.cpp:24:0:
/home/stowers/Programming/inpaint/inc/inpaint/gradient.h: In function ‘cv::Vec2f Inpaint::gradient(const Mat&, int, int)’:
/home/stowers/Programming/inpaint/inc/inpaint/gradient.h:44:19: error: expected primary-expression before ‘unsigned’
             m.ptr<unsigned char>(y-1),
```

**Comment by nzjrs** [comment]
the following file reproduces the error. Problem with `template<class ...>` implementation maybe?
```
#include <opencv2/highgui/highgui.hpp>
#include <iostream>

using namespace std;
using namespace cv;


template<class Mat>
Vec2f gradient(const Mat &m, int y, int x)
{
    const uchar *rows[3] = {
        m.at<uchar>(y-1),
        m.at<uchar>(y),
        m.at<uchar>(y+1)
    };

    const float gx = -1.f * rows[0][x-1] + 1.f * rows[0][x+1] + 
                     -2.f * rows[1][x-1] + 2.f * rows[1][x+1] + 
                     -1.f * rows[2][x-1] + 1.f * rows[2][x+1];

    const float gy = -1.f * rows[0][x-1] + -2.f * rows[0][x] + -1.f * rows[0][x+1] +
                      1.f * rows[2][x-1] +  2.f * rows[2][x] +  1.f * rows[2][x+1];

    return Vec2f(gx, gy);
}

int main(void)
{
    Mat img1 = imread("test.jpg",CV_LOAD_IMAGE_GRAYSCALE);
    gradient(img1, 5, 5);
}
```

**Comment by nzjrs** [comment]
the following two patches fix all build errors. Tests pass on Ubuntu 14.04 and g++4.8

```
diff --git a/inc/inpaint/gradient.h b/inc/inpaint/gradient.h
index 591b024..776f84a 100644
--- a/inc/inpaint/gradient.h
+++ b/inc/inpaint/gradient.h
@@ -41,9 +41,9 @@ namespace Inpaint {
     cv::Vec2f gradient(const Mat &m, int y, int x)
     {
         const uchar *rows[3] = {
-            m.ptr<uchar>(y-1),
-            m.ptr<uchar>(y),
-            m.ptr<uchar>(y+1)
+            m.template ptr<uchar>(y-1),
+            m.template ptr<uchar>(y),
+            m.template ptr<uchar>(y+1)
         };
 
         const float gx = -1.f * rows[0][x-1] + 1.f * rows[0][x+1] + 
@@ -82,4 +82,4 @@ namespace Inpaint {
 
 
 }
-#endif
\ No newline at end of file
+#endif
```

```
diff --git a/inc/inpaint/stats.h b/inc/inpaint/stats.h
index f394eaf..828cc8a 100644
--- a/inc/inpaint/stats.h
+++ b/inc/inpaint/stats.h
@@ -20,6 +20,8 @@
 #ifndef INPAINT_STATS_H
 #define INPAINT_STATS_H
 
+#include <algorithm>
+
 namespace Inpaint {
 
     /** Minimum of two */
@@ -69,4 +71,4 @@ namespace Inpaint {
     }
 
 }
-#endif
\ No newline at end of file
+#endif
```

**Comment by cheind** [comment]
ah yes, you are right...of course forget the template keyword there. MSVC is more relaxed as far as this is concerned. Will fix when I'm back home. Thanks for figuring out!

**Comment by cheind** [comment]
Thanks for your PR. Just merged, somehow I must have forgotten about this issue.
